sudo: false
language: node_js
node_js:
- "6"
- "5"
- "4"
cache:
  yarn: true
  directories:
  - node_modules/
before_install:
  - yarn global add nyc codecov
script:
  - yarn test
after_success:
  - nyc report --reporter=lcov > coverage.lcov && codecov
