title: JSData
description: Give your data the treatment it deserves with a framework-agnostic, datastore-agnostic JavaScript ORM built for ease of use and peace of mind. Works in Node.js and in the Browser.
google_analytics: UA-55528236-2
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
